//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomGeek.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentSelection
    {
        public int IDContentSelection { get; set; }
        public int IDSelection { get; set; }
        public Nullable<int> IDMovie { get; set; }
        public Nullable<int> IDGame { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual Selection Selection { get; set; }
    }
}
