//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomGeek.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreMovie
    {
        public int IDGenreMovie { get; set; }
        public int IDMovie { get; set; }
        public int IDMovieGenre { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual MovieGenre MovieGenre { get; set; }
    }
}
