//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomGeek.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.ContentSelection = new HashSet<ContentSelection>();
            this.GenreMovie = new HashSet<GenreMovie>();
        }
    
        public int IDMovie { get; set; }
        public int IDMovieType { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Screenwriter { get; set; }
        public string Producer { get; set; }
        public string Studio { get; set; }
        public string Country { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> BoxOffice { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> EpisodeCount { get; set; }
        public Nullable<int> SeasonCount { get; set; }
        public Nullable<double> Rating { get; set; }
        public int IDAgeRating { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual AgeRating AgeRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentSelection> ContentSelection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenreMovie> GenreMovie { get; set; }
        public virtual MovieType MovieType { get; set; }
    }
}
